version: '3'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash docker_start.sh
    environment:
      PORT: 4000
      DB_HOST: db
    links:
      - db
    depends_on:
      - db
    ports:
      - 4000:4000
    volumes:
      - .:/promote-gateway

  db:
    image: postgres:11-alpine
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "3306:3306"

volumes:
  db:
